# Using:
# If on Linx, run the following first
# export UID=$UID
#
# docker-compose -f docker-compose.rstudio.yml up -d 
# Open up http://hostname:8787
#
# To change the port, or you want to run multiple instances, specify the
# 2nd and on containers, run like so
# docker-compose -f docker-compose.rstudio.yml run -dp 8788:8787 rstudio
#
# The current directory will be mapped to /home/rstudio/seattle_flu
#
# Within the container, to install System packages
# Use the terminal within RStudio session and run
# sudo apt-get install -y <packge_name>
#
# To install R Packages, use the Package Manager
# within the RStudio session
# You may need system dependencies
# Any changes you make to running container it is good practice
# to add to the Dockerfile.RBuild.Env
#
# other useful commands:
# see what's up: docker-compose -f docker-compose.rstudio.yml ps
# bring container down: docker-compose -f docker-compose.rstudio.yml down -v
#
version: '3'
services:
  rstudio:
      build:
        context: .
        dockerfile: Dockerfile.RBuildEnv
        # The below can be used to circumvent firewall issues or
        # to use a caching proxy to reduce build times.
        #args:
        #  - "HTTP_PROXY=${HTTP_PROXY:-}"
        #  - "HTTPS_PROXY=${HTTPS_PROXY:-}"
        #  - "FTP_PROXY=${FTP_PROXY:-}"
      image: idm-docker-staging.packages.idmod.org/sfim_build_env:latest
      environment:
        - "DISABLE_AUTH=true"
        - "USERID=${UID:-1000}"
        - "GROUPID=${UID:-1000}"
        - "ROOT=TRUE"
      # Maps ports from Host -> Container
      # Here we hap host 8787 to container 8787.
      # Within the container RStudio runs on Port 8787
      ports:
        - "${HTTP_PORT:-8787}:8787"
      # Here we map host volumes to container volumes
      #
      # Notice in this compose we map in scripts and data even though
      # we added them in our dockerfile
      # This allows us to modify the script/data and run inside the container
      # and test new data or make changes to the script itself
      volumes:
      # This first volume allows you to pass your git config to the container
      # Most likely, you want to set the src path to /home/<username>/.gitconfig
      # On Windows, this file is located at C:\Users\<username>\.gitconfig
      # Be sure the .gitconfig file exists before mapping it in.
      #  - "${HOME}/.gitconfig:/home/rstudio/.gitconfig"
      # The following maps the pgpass and and pg_service.conf into the container
      #  - "${HOME}/.pgpass:/home/rstudio/.pg_pass"
      #  - "${HOME}/.pg_service.conf:/home/rstudio/.pg_service.conf"
      # The below maps in the local directory to the seattle_flu directory within the container
        - ./:/home/rstudio/seattle_flu
